name: Build MicroPython

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: build.py ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install toolchain (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi
          sudo apt-get install -y cmake
      - name: Check Versions
        run: |
          arm-none-eabi-gcc --version
          cmake --version
      - name: Build
        run: |
          make -C lib/micropython/mpy-cross -j2
          cd src
          make -j2
      - name: Upload hex file
        uses: actions/upload-artifact@v3
        with:
          name: MICROBIT-MICROPYTHON-${{ github.sha }}.hex
          path: src/MICROBIT.hex
